# This is the global base URL
baseURL = "https://agarciasoria.netlify.app/"
defaultContentLanguage = "en"
theme = "PaperMod"

# Global parameters that apply to both languages
[params]
    profileMode.enabled = true
    profileMode.imageWidth = 120
    profileMode.imageHeight = 120
    showLanguageSwitcher = true

# ==================================
# English Language Configuration
# ==================================
[languages.en]
    languageName = "English"
    languageCode = "en-us"
    weight = 1
    title = "Alejandro Garcia Soria | Professional Portfolio"

    [languages.en.params.profileMode]
        title = "Alejandro Garcia Soria"
        subtitle = "Theoretical Physicist | Educator | Lifelong Learner"
        imageUrl = "" 
        imageLink = "/about/"
        buttons = [
            { name = "About", url = "about/" },
            { name = "Documents", url = "documents/" }
        ]
    
    # English Menu
    [[languages.en.menu.main]]
        identifier = "about"
        name = "About"
        pageRef = "about" # Changed from url
        weight = 10
  #  [[languages.en.menu.main]]
  #      identifier = "blog"
  #      name = "Blog"
  #      pageRef = "posts" # Changed from url
  #      weight = 20
    [[languages.en.menu.main]]
        identifier = "documents"
        name = "Documents"
        pageRef = "documents" # Changed from url
        weight = 30

# ==================================
# Spanish Language Configuration
# ==================================
[languages.es]
    languageName = "Español"
    languageCode = "es"
    weight = 2
    title = "Alejandro Garcia Soria | Portfolio Profesional"

    [languages.es.params.profileMode]
        title = "Alejandro Garcia Soria"
        subtitle = "Físico Teórico | Educador | Aprendiz Permanente"
        imageUrl = ""
        imageLink = "/about/"
        buttons = [
            { name = "Sobre mí", url = "about/" },
            { name = "Documentos", url = "documents/" }
        ]

    # Spanish Menu
    [[languages.es.menu.main]]
        identifier = "about"
        name = "Sobre mí"
        pageRef = "about" # Changed from url
        weight = 10
#    [[languages.es.menu.main]]
#        identifier = "blog"
#        name = "Blog"
#        pageRef = "posts" # Changed from url
#        weight = 20
    [[languages.es.menu.main]]
        identifier = "documents"
        name = "Documentos"
        pageRef = "documents" # Changed from url
        weight = 30